const GITLAB_API = "https://gitlab.com/api/v4";
const TOKEN = process.env.GITLAB_TOKEN;
const PROJECT_ID = process.env.GITLAB_PROJECT_ID;

function headers() {
  return {
    "PRIVATE-TOKEN": TOKEN,
    "Content-Type": "application/json"
  };
}

export async function createFixMR(analysis) {
  const branchName = `pipelineiq-fix-${Date.now()}`;

  // Step 1 — get default branch
  const projectRes = await fetch(`${GITLAB_API}/projects/${PROJECT_ID}`, {
    headers: headers()
  });
  const project = await projectRes.json();
  const defaultBranch = project.default_branch || "main";
  console.log("Default branch:", defaultBranch);

  // Step 2 — create new branch
  await fetch(`${GITLAB_API}/projects/${PROJECT_ID}/repository/branches`, {
    method: "POST",
    headers: headers(),
    body: JSON.stringify({ branch: branchName, ref: defaultBranch })
  });
  console.log("Branch created:", branchName);

  // Step 3 — commit fix file
  const fixContent = `# PipelineIQ Auto Fix\n\n**Cause:** ${analysis.cause}\n\n**Fix:** ${analysis.fix_description}\n\n**Confidence:** ${analysis.confidence}/10\n\n*Generated by PipelineIQ at ${new Date().toISOString()}*`;

  await fetch(`${GITLAB_API}/projects/${PROJECT_ID}/repository/files/${encodeURIComponent("PIPELINEIQ_FIX.md")}`, {
    method: "POST",
    headers: headers(),
    body: JSON.stringify({
      branch: branchName,
      content: fixContent,
      commit_message: `fix: PipelineIQ auto-fix — ${analysis.cause.slice(0, 60)}`
    })
  });
  console.log("Fix file committed");

  // Step 4 — open MR
  const mrRes = await fetch(`${GITLAB_API}/projects/${PROJECT_ID}/merge_requests`, {
    method: "POST",
    headers: headers(),
    body: JSON.stringify({
      source_branch: branchName,
      target_branch: defaultBranch,
      title: `[PipelineIQ] Auto-fix: ${analysis.cause.slice(0, 60)}`,
      description: `## PipelineIQ detected a pipeline failure\n\n**Root cause:** ${analysis.cause}\n\n**Suggested fix:** ${analysis.fix_description}\n\n**Confidence score:** ${analysis.confidence}/10\n\n---\n*This MR was opened automatically by PipelineIQ AI Agent*`,
      labels: "pipelineiq,auto-fix"
    })
  });

  const mr = await mrRes.json();
  console.log("MR opened:", mr.web_url);
  return mr;
}